### ISSUE TITLE
Specify location to save kube config 

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke#1040]
When running rke up it will save a kube config file. It would be useful (for automation) to include a way to specify where to save that file too.

**Comment by Oats87** [comment]
One issue with this is that RKE expects the kube_config to be in the local directory where RKE is being invoked due to the fact that it uses it to pull state from the Kubernetes cluster. I suppose as time progresses and we move to state outside of Kubernetes, a `--workdir` option may provide to be useful.
