### ISSUE TITLE
RKE should not cause re-deployment of critical Kubernetes system services if not explicitly instructed to do so

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1062]
While performing an `rke up` with a config change down the line, RKE will proceed to reconcile all component addons (ingress, network, DNS, etc.). Most of the time this does not cause issues; however, if the user has made any change to the addon deploy resultant product, the `kubectl apply` will update the addon and the controller (daemonset, deployment, etc.) will perform an upgrade of the specified addon.

This can be extremely disruptive to Kubernetes cluster that are serving production workloads where we should not have any interruption to workloads for Kubernetes patch release upgrades (1.11.3 -> 1.11.5).

This could potentially be solved by adding some style of flag for the `rke up` to instruct RKE to reconcile critical system services only when explicitly told to do so, or during minor version upgrades (1.10 -> 1.11) of Kubernetes. This can be like `rke up --reconcile-addon=ingress,nginx`

**Comment by alena1108** [comment]
@Oats87 

Kubectl will redeploy the daemonset and deployment only when something got changed in the spec. And we should always reconcile to the state that is defined on the rke config. Dropping the part of the state upgrade just doesn't seem right.

If the issue is with us deploying the addon v1, and then user doing the modifications for the addons on k8s side so it becomes v2, and wanting to drop the subsequent updates, then we should resolve it differently. If more customization is required for various addons supported by rke, we should enable those via extra args

**Comment by deniseschannon** [comment]
I agree with @alena1108. By default, we should upgrade and reconcile to whatever is in the cluster.yml esp if the spec has changed.

Are we saying that RKE re-deployed even though no add-on had been changed? @Oats87
