### ISSUE TITLE
nginx-ingress-controller daemonset is different between versions 0.10.2 and 0.16.2 and breaks if RKE is updated 

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1091]
**RKE version:**
N/A. All RKE versions that have included `0.16.2` have this problem.

**cluster.yml file:**

**Description:**
If a user installs an Kubernetes cluster using an older version of RKE with kubernetes version (for example, `v1.10.5-rancher1-1` (which contains `rancher/nginx-ingress-controller:0.10.2-rancher3`), they will successfully install for this version of the nginx ingress controller because the daemonset template was properly configured for it. 

If the user updates their RKE (or Rancher) to one that has the daemonset template set up for the `0.16.2-rancher1` version of the nginx-ingress-controller, when `rke up` is run it will reconcile the ingress controller addon with the 0.16.2-rancher1 compatible version of nginx ingress (but will still use the 0.10.2-rancher3 image) which means that the nginx ingress controller will go into a bad state because of the lack of permissions.

**Steps to Reproduce:**
Create a cluster using rke with a version that uses the old daemonset template
Update your RKE and then update (but keeping the version of k8s in place/the same so to use the old 0.10.2 nginx IC)
Watch the nginx ingress controller get updated and start to crashloopbackoff due to permissions problems

**Comment by aemneina** [comment]
rancher/rancher:v2.1.3 was in use when this was hit.

**Comment by orangedeng** [comment]
@Oats87 @alena1108 I think that the root cause is that, nginx ingress controller with version < 0.16.0 can not support securityContext. So when we attempt to apply the new daemonSet yaml to the old version ingress controller, the pod of ingress will throw an error like:
```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    154a606-dirty
  Build:      154a606
  Repository: git@github.com:rancher/ingress-nginx.git
-------------------------------------------------------------------------------

F0129 10:10:40.867081       8 main.go:59] Port 80 is already in use. Please check the flag --http-port
```
So we need to change rke to apply the old template of the nginx ingress daemonSet.

**Comment by orangedeng** [comment]
@Oats87 @alena1108 I think that the root cause is that, nginx ingress controller with version < 0.16.0 can not support securityContext. So when we attempt to apply the new daemonSet yaml to the old version ingress controller, the pod of ingress will throw an error like:
```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    154a606-dirty
  Build:      154a606
  Repository: git@github.com:rancher/ingress-nginx.git
-------------------------------------------------------------------------------

F0129 10:10:40.867081       8 main.go:59] Port 80 is already in use. Please check the flag --http-port
```
So we need to change rke to apply the old template of the nginx ingress daemonSet.

**Comment by alena1108** [comment]
Can be tested in v0.2.0-rc5

**Comment by sangeethah** [comment]
@sowmyav27  To reproduce the issue , Create a k8s cluster using some rancher server version which has nginx-ingress-controller version set to `0.10.2`  and then upgrade to `rancher/rancher:v2.1.3`. then Trigger a rancher up ( by may be adding another control node) , you should see this problem reproduce.

**Comment by sangeethah** [comment]
@sowmyav27  To reproduce this issue follow these steps:

1. Create a cluster using rke version - v0.1.8
2. Once cluster creation is done, check that inginx-ingress-controller version is `0.10.2`.
3. Use  rke version - v0.1.9 and try to update the above cluster (do not change kubernetes cluster version)

You should see  the nginx ingress controller get updated and start to crashloopbackoff due to permissions problems.

**Comment by sowmyav27** [comment]
With the steps mentioned, I was not able to reproduce the issue.

Using  rke version - v0.1.9, the nginx ingress controller did not crash.

**Comment by Oats87** [comment]
@sangeethah @sowmyav27 can you provide the `cluster.yml` you used to test this?

You need to pin down the Kubernetes version to use the set of images based on that Kubernetes version from types. Note that given the `rke cli` behavior, you will need to specify `system_images` for this.

**Comment by sowmyav27** [comment]
reproduced the issue on rancher:v2.0.6
Waiting for issue -[https://github.com/rancher/rancher/issues/18277] to be fixed.

**Comment by sowmyav27** [comment]
waiting for issue - https://github.com/rancher/rancher/issues/18608 to be fixed.

**Comment by sowmyav27** [comment]
verified while upgrading from ranvher v2.0.6 to master. No error was found in the ingress controller.
<img width="1063" alt="Screen Shot 2019-03-08 at 3 44 09 PM" src="https://user-images.githubusercontent.com/26032343/54062149-3d04f100-41b9-11e9-96aa-5662b996ca12.png">
