### ISSUE TITLE
Refactor to pluggable cloud providers

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1109]
See https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider/cloud-provider-refactoring.md and https://github.com/kubernetes/enhancements/issues?q=is%3Aissue+is%3Aopen+out+of+tree+label%3Asig%2Fcloud-provider

Targeted for 1.14 but don't think the in-tree ones will be removed immediately.

**Comment by mkjpryor-stfc** [comment]
Is there any plan to look at moving to the external cloud providers for RKE?

It is currently very difficult to deploy RKE clusters on Openstack with the cloud provider enabled when the nodes have multiple NICs. The `[Networking]` section referred to in #1210 would solve this.

**Comment by SvenMW** [comment]
@superseb  any updates on this?

as far as I'm aware currently only the deprecated "internal" openstack cloudprovider is supported and thus e.g. no feature like application credentials works.

Thanks

**Comment by remche** [comment]
@superseb any progress on this ?
I'm main dev of [terraform-openstack-rke](https://github.com/remche/terraform-openstack-rke), and Openstack Train+ users are stuck because kubernetes/kubernetes#96673 is not backported for now. I any case, k8s 1.22 is coming soon...

Do you plan any work on this or let users deploy the ccm/csi plugins by themselves once in-tree providers are dropped ?
