### ISSUE TITLE
Support for CoreDNS proxy configuration

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#1645]
**RKE version:**
v0.2.8

**Description**
This is an enhancement request to support additional configuration options for CoreDNS. According to https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#configuring-coredns , the following configuration options are available:
```yaml
dns:
    provider: coredns
    upstreamnameservers:
    - 1.1.1.1
    - 8.8.4.4
```
In addition to upstream nameservers, would like to have the ability to specify a proxy definition. Specifically, something that will allow integration with Consul DNS (see https://www.consul.io/docs/platform/k8s/dns.html#coredns-configuration )

**Workaround**
As a workaround, the coredns ConfigMap in the kube-system namespace can be manually edited to add this configuration. However, this configuration could get wiped out if a CoreDNS upgrade requires a new ConfigMap.

gz#10441

**Comment by ekristen** [comment]
I would like to see this as well. Ideally overriding the entire core file would be best. There are a number of things that can be additionally configured and trying to support only proxy or specific directives limits options. 

I have the need to use the template directive specifically.

**Comment by nneul** [comment]
Similar need for being able to specify rewrite rules to allow custom DNS overrides of otherwise externally resolved names, such as to override dns name of external load balancers with cluster internal address to avoid a hairpin. 

https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/

**Comment by krausexb** [comment]
This feature is very important to a lot of users, since rke clusters with default coredns configuration files provocate a ton of NXDOMAINS, since the default nodes search domain is used. In the combination with ndots:5 default value almost every dns query will be extended with your companys search domain. This results in querys like github.com.my.company.com.

Run a TCP Dump to see it in action:
script -q -c "tcpdump -i any -l port 53 2>/dev/null | grep --line-buffered ' A? ' | cut -d' ' -f8" | tee dns.log

**Comment by badihi** [comment]
Custom config for CoreDns would be very useful in many cases. Please put it on the roadmap.

**Comment by danfoley1991** [comment]
classic, closing with no resolution
