### ISSUE TITLE
[Feature Request] podman support

### ISSUE THREAD

**Issue by kaplan-michael** [rancher/rke#2306]
Hey,
Have you considered supporting podman?
Thanks!

**Comment by Thulium-Drake** [comment]
This would really be interesting indeed. For one, it will end any problems with people trying to run RKE environments airgapped from the Internet against internal registries (as non-redhat/project atomic docker can't live without docker.io).

And it's supposedly compatible with Docker for the most part, without the centralized daemon, so less overhead.

**Comment by kaplan-michael** [comment]
I can test it out, but it seems that rke binary v1.2.1 ignores `ignore_docker_version: true` in cluster.yml

**Comment by vincent99** [comment]
The "centralized daemon" is the part that's useful for other software to integrate with it, and lack of it is why this won't work.  RKE talks to the unix domain socket (/var/run/docker.sock) for the daemon to tell it to do things, rather than shelling out to the CLI (as would be the only option for podman).

And this has nothing to do with the docker _registry_, even if you could run containers through podmain you'd still need them to all come from somewhere and ours are on dockerhub.

**Comment by Thulium-Drake** [comment]
> I can test it out, but it seems that rke binary v1.2.1 ignores `ignore_docker_version: true` in cluster.yml

That's probably because you need to configure this: 
* https://podman.io/blogs/2020/07/01/rest-versioning.html 
* https://liquidat.wordpress.com/2020/04/20/howto-using-the-new-podman-api/



> The "centralized daemon" is the part that's useful for other software to integrate with it, and lack of it is why this won't work. RKE talks to the unix domain socket (/var/run/docker.sock) for the daemon to tell it to do things, rather than shelling out to the CLI (as would be the only option for podman).
> 

See above, Podman has a REST API for exactly this reason
> And this has nothing to do with the docker _registry_, even if you could run containers through podmain you'd still need them to all come from somewhere and ours are on dockerhub.

While you make a good point, it isn't all about the registries. But Podman's ```registries.conf``` makes life a lot easier in airgapped environments. I spent a full week looking for a way to make upstream Docker CE _NOT_ pull images from Docker.io, but from our internal Nexus Dockerhub Proxy. I ended up switching Docker engines to the one by Project Atomic/Red Hat, as it allows me to block certain registries (or in our case, all of them)

https://github.com/containers/image/blob/master/registries.conf

But in the view of the Docker devs, this is for some reason not desirable (which, in my views, makes Docker unfit for enterprise use)

**Comment by kaplan-michael** [comment]
> That's probably because you need to configure this:
API is working fine when testing with curl. rke checks fail because podman reports version [2.1.1]
which results in this error  `FATA[0001] Unsupported Docker version found [2.1.1] on host [], supported versions are [1.13.x 17.03.x 17.06.x 17.09.x 18.06.x 18.09.x 19.03.x] ` even if `ignore_docker_version: true` is set

**Comment by vincent99** [comment]
That is indeed new(er) and I hadn't seen before, but no longer "without the centralized daemon" which was their one main feature...

If you don't want to talk to external registries, the usual method is "physically" blocking the network traffic, not finding software that has options to ask politely that they not be used by rewriting requests being the scenes.

RKE and Rancher both have options to say that all system images should come from a private registry, without remapping everything in the container runtime daemon on every node.

https://rancher.com/docs/rke/latest/en/config-options/private-registries/

https://rancher.com/docs/rancher/v2.x/en/admin-settings/config-private-registry/

(and k3s, which has its own containerd instead of docker; https://rancher.com/docs/k3s/latest/en/installation/private-registry/)

**Comment by Thulium-Drake** [comment]
> That is indeed new(er) and I hadn't seen before, but no longer "without the centralized daemon" which was their one main feature...
> 
From what I gather, it's not a daemon and only there to facilitate tools that expect a Docker-like API and allow them to function.

> If you don't want to talk to external registries, the usual method is "physically" blocking the network traffic, not finding software that has options to ask politely that they not be used by rewriting requests behind the scenes.
> 
True, however, I have 2 issues with how Docker functions under those circumstances (with all access to the internet blocked):

1. It requires _all_ Helm charts/compose-files etc.. to be updated with a new image path:
 library/hello-world -> myinternalrepo.intra.example.corp/library/hello-world
 And this places an administrative burden on the devs that should not be of any concern to them.
2. It complains about each and every request that does not mention a registry where to gather it from

In the current setup I have (with Project Atomic's fork of Docker), I disabled all registries and only allowed the daemon to access my internal registry. And due to how this works, we no longer have to edit _all_ manifest files (helm etc.). We have set up Nexus to be the overarching 'catch-all' proxy for all upstream registries we wish to allow (granular) access to, which allows us all the control we need.

> RKE and Rancher both have options to say that all system images should come from a private registry, without remapping everything in the container runtime daemon on every node.
> 
> https://rancher.com/docs/rke/latest/en/config-options/private-registries/
> 
> https://rancher.com/docs/rancher/v2.x/en/admin-settings/config-private-registry/
> 
Yes, tried those, they still require the fully qualified image names -> ```repo.internal.corp/namespace/image:version``` Also does not work with password protected registries :-(

Read #2304 for an issue where I can download images using the docker cli, but not via RKE.

> (and k3s, which has its own containerd instead of docker; https://rancher.com/docs/k3s/latest/en/installation/private-registry/)

Looks interesting, I'll read up on it a bit more.

**Comment by fpicot** [comment]
Another reason to support podman is that docker has been removed from RHEL 8 and derivatives in favor of podman : https://access.redhat.com/solutions/3696691

**Comment by steve-todorov** [comment]
I would also like to join the crowd and suggest `podman` should be supported. Together with a few colleagues we have also wasted more than a week in miserable failures trying to "fix" what Docker developers are simply **refusing** to allow. Their "registry mirrors" option does not work with authentication and this is something they, unfortunately completely reject on fixing. There are even PRs from SUSE and RedHat which specifically fix this issue, but have been closed/rejected as well.

I invested quite some time in the past few days to research on `podman` and their developers have specifically stated on a few occasions they are aiming at making `podman` as compatible with `docker` as possible (i.e. https://github.com/testcontainers/testcontainers-java/issues/2088#issuecomment-594153903). As mentioned above, podman has a compatible API. If you use `systemcl enable podman` it would have added as `/run/podman/podman.sock`. There's also an additional package available on some distributions called `podman-docker` which adds `/var/run/docker.sock`.

**Comment by Negashev** [comment]
Now podman is even more docker-like
https://www.redhat.com/sysadmin/podman-docker-compose

```
$ sudo systemctl enable --now start podman.socket
$ sudo curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping
OK
```

**Comment by steve-todorov** [comment]
Ha! That's pretty cool! I'll have to check this out again. Thanks for mentioning it! :)

**Comment by Thulium-Drake** [comment]
@superseb Hi Sebastiaan,

Is this on the roadmap for RKE somewhere in the (distant/nearby) future? :-)

**Comment by Thulium-Drake** [comment]
bump, this is still something worth looking in to. :-)

**Comment by ifelsefi** [comment]
Please add podman support.   It's not sustainable to require docker when it has been dropped by Redhat and various forks.

**Comment by remixmabix** [comment]
+1 for this feature

**Comment by Thulium-Drake** [comment]
@galal-hussein @superseb 

I'd be really nice if one of the Rancher folks could reply on this to know what the plans are, if any :-)

**Comment by scott-ling** [comment]
Indeed, and update one way or the other would be nice.

As this is a blocker for me and a few organizations I work with as all have removed Docker in favor of podman. (as are many others these days.)

**Comment by vincent99** [comment]
There are no planes for this that I'm aware of; given that rke2 and k3s use/bundle containerd, that is the direction we're going.

**Comment by kaplan-michael** [comment]
Closing this issue, as @vincent99 said it probably doesn't make sense to implement it.

**Comment by ifelsefi** [comment]
How does it not make sense to support the default container runtime of RHEL and derivatives?

**Comment by kaplan-michael** [comment]
I don't see rancher implementing this, as they are moving in a direction of bundled runtime(containerd). 
It could of course be added by someone, but as this has been open for quite a while and we haven't seen any progress I would say it's not going to happen. 

NOTE: Kubernetes from version 1.2 doesn't support docker and deprecating docker in 1.23(in favor of  CRI standard runtimes)

**Comment by vincent99** [comment]
Even back when Docker was the default(/only) runtime most  users installed the (newer) community editions instead of the upstream RHEL packages.

**Comment by jeanluclariviere** [comment]
Just wanted to throw my +1 on this. The fact that docker has been replaced in favor of podman for RHEL8 is the driving factor behind this.

**Comment by dm17** [comment]
Are there any light weight k8s alternatives that support podman?

**Comment by Thulium-Drake** [comment]
I eventually ended up building a cluster using KubeAdm with CRI-O as the container engine, works like a charm :)

**Comment by dm17** [comment]
@Thulium-Drake thanks - I'm looking for a baremetal option and KubeAdm and the like or oriented towards VMs?

**Comment by Thulium-Drake** [comment]
Indeed, I'm wrapping it in Ansible over here: https://github.com/Thulium-Drake/ansible-role-k8s

You still need to configure the whole cluster content afterwards (CNI, storage plugins etc), but this role will set up VMs with just plain k8s and CRI-O as the engine.

**Comment by idc77** [comment]
I'm so tired of this.
So tired.
RKE has issues pretty much everywhere, but the only OS that actually works is Micros, or so you might think, because there is no docker in micros.
And the arrogance of not supporting podman is just over the top

**Comment by dm17** [comment]
> I'm so tired of this. So tired. RKE has issues pretty much everywhere, but the only OS that actually works is Micros, or so you might think, because there is no docker in micros. And the arrogance of not supporting podman is just over the top

Can't really force development hours from FOSS devs... I agree that the splittering in this domain is over the top, but everyone is trying to build their own business moat. I've stuck with `compose` in docker & podman for this very reason.
