### ISSUE TITLE
Which the differences between the rancher1 series of system images and the rancher2 series?

### ISSUE THREAD

**Issue by IJOL** [rancher/rke#2319]
HI, we used RKE v1.1.3 to build a cluster, that ended having rancher/hyperkube 1.18.3-rancher2, we need to upgrade ASAP or in the case build a new one with v1.18.5 or up, and we only see a rancher/hyperkube:v1.18.9-rancher1 one, and we wonder if we can use this image instead of the rancher2 one.. so hence the question, what are the differences between rancher2 tagged images and rancher1 ones..

**Comment by superseb** [comment]
Any image higher than `rancher1` only exists if we needed to repackage the same version because of a change. In case of 1.18.3, this was because we added the Windows images as seen in https://github.com/rancher/hyperkube/compare/v1.18.3-rancher1...v1.18.3-rancher2.

The released RKE binaries always have the latest released versions available, retrievable by using `rke config -l -a`.

**Comment by IJOL** [comment]
Just learn something, we ca use safely the latest 1.2.2-rcX release to
update our cluster, or we go simply updating the system images set and do a
rke up with the same version we used for the cluster build, which is a
better path to update our rke cluster?


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega
