### ISSUE TITLE
Azure cloud-config misses `SecurityGroupResourceGroup` value

### ISSUE THREAD

**Issue by aslafy-z** [rancher/rke#2610]
**RKE version:** v1.2.9

**Docker version: (`docker version`,`docker info` preferred)** N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Azure

**cluster.yml file:** N/A

**Steps to Reproduce:** N/A

**Results:** N/A

`SecurityGroupResourceGroup` allows to specify resource group of the security group resource where rules can be added.

See https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/#cluster-config

**Comment by jiaqiluo** [comment]
### Root cause

The upstream Azure cloud-config supports the option `SecurityGroupResourceGroup`, but REK does not have it in the internal `AzureCloudProvider` struct, so the value is ignored. 
 

### What was fixed, or what changes have occurred
add it to RKE's internal data structure 

### Areas or cases that should be tested
When creating a cluster with Azure as the cloud provider, we can now set the `SecurityGroupResourceGroup` ( see [RKE Docs](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/azure/))

And according to [the upstream docs](https://cloud-provider-azure.sigs.k8s.io/install/configs/#cluster-config:~:text=the%20cluster%E2%80%99s%20subnet-,securityGroupResourceGroup,of%20the%20resource%20group%20that%20the%20security%20group%20is%20deployed%20in,-routeTableName), it is used as the name of the security group's resource group. 
 

 
### What areas could experience regressions?
Creating a cluster with Azure as the cloud provider with or without setting `SecurityGroupResourceGroup` should work.

**Comment by jiaqiluo** [comment]
Waiting for the next RC - v1.4.0-rc2

**Comment by jiaqiluo** [comment]
Can be validated in `v1.4.0-rc3`

**Comment by thaneunsoo** [comment]
### Test Environment: ###
RKE version: v1.4.0-rc3
Cloud Provider: Azure

----------

### Testing: ###
Tested the issue with the following steps:
1. Add `securityGroupResourceGroup` to cloud_provider cloud-config in cluster.yml file
2. Run `rke up --config cluster.yml`

Tested the following testcases:
- rke up with no cloud_provider configs
- rke up with basic cloud_provider configs
- rke up with `securityGroupResourceGroup` cloud_provider config
- Provision azure cluster on Rancher UI and grab config values to put into cluster.yml

**Result**
I seem to be able to provision when there are no cloud_provider configs and within the Rancher UI, but when I try to create a cluster with the cloud_provider configs added into the cluster.yml, even with the correct values (based on Rancher documentation AND from pulling values from active rke1 azure cluster from Rancher UI), I seem to always hit a health check failure on kubelet towards the end of the `rke up` command. 
```
FATA[0199] [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [ip_address]: Get "http://localhost:10248/healthz": Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: ERROR: Please run 'az login' to setup account.] 
```

**Comment by jiaqiluo** [comment]
I confirmed with @thaneunsoo that the same test also failed when using RKE 1.3.15, which means it is an existing bug if it is a bug.

**Comment by jiaqiluo** [comment]
This is not a bug.  Please see [this comment](https://github.com/rancher/rke/issues/2611#issuecomment-1279614197) for details 

Moving it back to to-test

**Comment by thaneunsoo** [comment]
### Test Environment: ###
RKE version: v1.4.0-rc3
Cloud Provider: Azure

----------

### Testing: ###
Tested the issue with the following steps:
1. Add `securityGroupResourceGroup` to cloud_provider cloud-config in cluster.yml file
2. Run `rke up --config cluster.yml`

**Result**
The resource group is set correctly.
![image.png](https://zube.io/files/rancher/d001a57d8355f012b0d00889c25c018b-image.png)
