### ISSUE TITLE
rke v1.4.3-rc1 fails to provision a k8s v1.25 successfully.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rke#3126]
**RKE version: 1.4.3-rc1**

**Docker version: 20.10.21 (`docker version`,`docker info` preferred)**

**Operating system and kernel: Ubuntu 20.04.4 LTS (AWS AMI : ami-0eea504f45ef7a8f7)**
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Type/provider of hosts: AWS**

**Steps to Reproduce:**

1. Create a 3 t3.medium/large instances on AWS.
2. With RKE v1.4.3-rc1 describe 1cp, 1etcd, 1wk nodes.
3. Provide k8s v1.25.2-rancher1-1 in the cluster.yaml file.
4. Create a cluster with `rke up`.

**Results:**
Cluster creation log stops with error - 
`FATA[0201] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`

Events for the job show the warning `BackoffLimitExceeded`
`Warning  BackoffLimitExceeded  2m19s                  job-controller  Job has reached the specified backoff limit`

calico-kube-controllers pod show following error in the events.
```
Events:
  Type     Reason           Age                     From               Message
  ----     ------           ----                    ----               -------
  Normal   Scheduled        9m45s                   default-scheduler  Successfully assigned kube-system/calico-kube-controllers-99d7bbb84-4z6xz to etcd
  Warning  NetworkNotReady  9m43s (x3 over 9m46s)   kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
  Normal   Pulled           8m59s (x3 over 9m40s)   kubelet            Container image "rancher/mirrored-calico-kube-controllers:v3.22.0" already present on machine
  Normal   Created          8m58s (x3 over 9m40s)   kubelet            Created container calico-kube-controllers
  Normal   Started          8m58s (x3 over 9m40s)   kubelet            Started container calico-kube-controllers
  Warning  Unhealthy        8m50s (x10 over 9m39s)  kubelet            Readiness probe failed: Failed to read status file /status/status.json: unexpected end of JSON input
  Warning  BackOff          4m43s (x22 over 9m18s)  kubelet            Back-off restarting failed container
```

**Comment by sowmyav27** [comment]
@vivek-infracloud Can you check RKE v1.4.3-rc1 provisioning using k8s 1.24 ?

**Comment by vivek-shilimkar** [comment]
@sowmyav27 I did check that yesterday, and v1.24 is provisioning successfully.

**Comment by jiaqiluo** [comment]
I got the `cluster.yml` from @vivek-infracloud  and noticed that 
1) it has the line `kubernetes_version: ""`, so rke will use the default version, v1.24.8-rancher1-1, when provisioning a cluster.
2) it has the section `system_images` which specifies specific image to use for each component

Then I did the following tests:
1. copy your cluster.yml, replace nodes, run rke up  - Results: the cluster is provisioned successfully
2. copy your cluster.yml, replace nodes, add  kubernetes_version: "v1.25.2-rancher1-1" , run rke up  - Results: the cluster is provisioned failed, I see the exact same error as your saw
3. copy your cluster.yml, replace nodes, add  kubernetes_version: "v1.25.2-rancher1-1" , drop the  system_images section, run rke up  - Results: the cluster is provisioned successfully

This makes me believe that the problem comes from the `cluster.yaml`: the values under the `system_images` section are inaccurate for version v1.25.2-rancher1-1.
 

Can you try it again and let me know how it goes?

**Comment by markusewalker** [comment]
I'm unable to reproduce this on my end. Using RKE 1.4.3-rc1, I can deploy a K8s 1.25 cluster. Additionally, I can also use 1.4.3-rc1 to upgrade from 1.24.8 to 1.25.2. As @jiaqiluo, the issue most likely is the `cluster.yml` that is used.

@vivek-infracloud can you try @jiaqiluo's suggestion above and if a non-issue, close the issue? Thanks!

**Comment by vivek-shilimkar** [comment]
Validated the issue again with following scenarios.

**Scenario 1**
After running `rke config` provided the necessary inputs along with the `Kubernetes Docker image = vrancher/hyperkube:v1.25.2-rancher1`. `system_images` section gets added automatically afterwards.

**_Note: kubernetes_version is not added here._**

Running the `rke up` up command throws the error mentioned in the issue.
Some of the image versions on failed to provision cluster are as follows.
```
Image:          rancher/mirrored-calico-kube-controllers:v3.22.0
Image:          rancher/calico-cni:v3.22.0-rancher1
Image:          rancher/mirrored-calico-node:v3.22.0
```

_I have been creating a standalone RKE cluster as mentioned in the Scenario 1, where system_images section gets added automatically and cluster provisions successfully. However, in case of RKE v1.4.3-rc1 it failed._

**Scenario 2**
Added kubernetes_version = v1.25.2-rancher1-1 in the cluster.yml **keeping the system_images section as it is**. In this scenario log shows the cluster provisioning to be successful but many pods remain in ContainerCreating or CrashLoopBackOff state.
![Screenshot from 2022-12-23 12-43-58](https://user-images.githubusercontent.com/83208989/209295055-1f5ad752-7eba-416f-8723-9a988288d023.png)

**Scenario 3** - As suggested by @jiaqiluo in this [comment](https://github.com/rancher/rke/issues/3126#issuecomment-1361691343) (Number 3)

Removed the system_images section and provided the kubernetes_version = v1.25.2-rancher1-1. Cluster provisioning was successful as observed by @jiaqiluo and @markusewalker. However, the image versions are different than above scenario.
```
Image:         rancher/mirrored-calico-kube-controllers:v3.24.1
Image:         rancher/calico-cni:v3.24.1-rancher1
Image:         rancher/mirrored-calico-node:v3.24.1
```

**Comment by vivek-shilimkar** [comment]
Why `system_image` versions are different in Scenario 1 and Scenario 3?

@sowmyav27 @jiaqiluo @markusewalker 
The scenario 1 have been working fine until RKE v1.4.3-rc1. In my opinion that should keep working. If it is okay for that scenario not to work, we can close this issue.

**Comment by jiaqiluo** [comment]
@vivek-infracloud 
[ v1.24.8-rancher1](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.7/rke/k8s_rke_system_images.go#L8334) and [v1.25.2-rancher1](https://github.com/rancher/kontainer-driver-metadata/blob/48d1d9a582d05129fe624a127d34e251347f7ee8/rke/k8s_rke_system_images.go#L8378) use two different set of system images.  
In scenario 1 and 2, when you generated the cluster.yml by using `rke config` you did not set the Kubernetes version, so RKE uses the set of system images for the default version `v1.24.8-rancher1`, which does not work when you set the version to  `v1.25.2-rancher1` afterward.  

Let me know if this makes sense to you.

**Comment by vivek-shilimkar** [comment]
In Scenario 2, I did specify the kubernetes version. 

> In this scenario log shows the cluster provisioning to be successful but many pods remain in ContainerCreating or CrashLoopBackOff state.

**Comment by jiaqiluo** [comment]
Your comment mentioned " keeping the system_images section as it is.", which makes me think you are using the cluster.yml generated in scenario 1.  If that is true, your cluster.yml contains the system-images for v1.24.8-rancher1, so you observed errors after you added `kubernetes_version: v1.25.2-rancher1-1` and ran `rke up`

**Comment by vivek-shilimkar** [comment]
Okay, I understand why I see those errors. 

However, as mentioned before, _I have been creating a standalone RKE cluster as mentioned in the Scenario 1, where system_images section gets added automatically and cluster provisions successfully. However, in case of RKE v1.4.3-rc1 it failed._ 

The scenario 1 have been working fine until RKE v1.4.3-rc1. In my opinion that should keep working. If it is okay for that scenario not to work, we can close this issue.

**Comment by sowmyav27** [comment]
@vivek-infracloud As Jack mentions, `rke config` uses default k8s version's system images which is 1.24.8 and that will not work and is expected. 

I think this is happening because you are trying to deploy k8s on 1.25 when the default system images are pointing to 1.24 instead.

If we tag an RKE with 1.25 as default, then you should be able to provision rke standalone using `rke config`. 

And as per `Scenario 1`, even though you enter `Kubernetes Docker image = vrancher/hyperkube:v1.25.2-rancher1`, kubernetes version is not set in cluster.yml file. which means the the system images generated are for 1.24 k8s _only_.

On that note @jiaqiluo how can i get k8s 1.25's system images when using `rke config` ? Is that a bug in RKE ?

**Comment by jiaqiluo** [comment]
I dug into the code and found a way to get the right images for 1.25, but RKE prompts a misleading message which in my option should be fixed.
When running `rke config` and seeing the following question 
```
[+] Kubernetes Docker image [rancher/hyperkube:v1.24.8-rancher1]:
```
enter the k8s version you want to use, like this 
```
[+] Kubernetes Docker image [rancher/hyperkube:v1.24.8-rancher1]: v1.25.2-rancher1-1
```
You should get the right images for the version in the generated config file. 

Note: the version must be in the supported version list. Otherwise, the default version will be used. 
```
> ./rke config -l -a
WARN[0000] This is not an officially supported version (v1.4.3-rc1) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases
v1.25.2-rancher1-1
v1.23.14-rancher1-1
v1.24.8-rancher1-1
```

**Comment by sowmyav27** [comment]
> but RKE prompts a misleading message which in my option should be fixed.

@vivek-infracloud Can you log a separate bug for this? Otherwise this issue can be closed after you confirm the prev comments and the current behavior ^

**Comment by vivek-shilimkar** [comment]
I have been following the same steps as mentioned by @jiaqiluo [here](https://github.com/rancher/rke/issues/3126#issuecomment-1367507792). 

However I tested again and provided the k8s version 
`[+] Kubernetes Docker image [rancher/hyperkube:v1.24.8-rancher1]: v1.25.2-rancher1-1` 
like above but the cluster provisioning fails. Which means the system_images for the k8s v1.25.2-rancher1-1 are not getting generated in the cluster.yml file.

@sowmyav27 I will log a separate issue for above behaviour and close this issue.
