### ISSUE TITLE
Question: Change ETCD database mount

### ISSUE THREAD

**Issue by limod** [rancher/rke#3197]
Hi!

I have a question about changing the path for the etcd database in the etcd docker container.
Background: I want the etcd database to run on a separate SSD because of performance problems with etcd.

This is the default mount for the etcd container in Fedora Coreos (docker inspect):
```
"Source": "/opt/rke/var/lib/etcd",
"Destination": "/var/lib/rancher/etcd"
```

I looked up in the source code how the source path is created:

`plan.go fmt.Sprintf("%s:%s:z", path.Join(host.PrefixPath, "/var/lib/etcd"), services.EtcdDataDir)`
With host.PrefixPath == CoreOSPrefixPath == "/opt/rke"

I found no way in the code to configure it, how could i change the path from **"/opt/rke/var/lib/etcd",** to e.g. **"/var/mnt/var/lib/etcd"** to move my etcd database to another disk?

Thanks for any suggestions/ideas!

**RKE version:**

kubernetes_version: "v1.21.6-rancher1-1"
rke version v1.3.2

**Docker version: (`docker version`,`docker info` preferred)**

20.10.9

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Fedora CoreOS 5.14.14-200.fc34.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Comment by FlyingOnion** [comment]
Try adding `prefix_path: /var/mnt` in cluster.yml
The [official example](https://rancher.com/docs/rke/latest/en/example-yamls/) does not mention this field, but `RancherKubernetesEngineConfig` does include `PrefixPath` and `WindowsPrefixPath` fields to set custom prefix.

If `PrefixPath` is set, `(*Cluster).getPrefixPath` will return this value instead of default `"/"`.

Then, `(*Host).SetPrefixPath` will set this value using the first case
`case clusterPrefixPath != "/"`
instead of case
`case strings.Contains(h.DockerInfo.OperatingSystem, CoreOS)`

I'm not official developer. I looked up the code. Hope this helps.

Not sure whether other configs will change or not if this field is set. Better check it carefully :)

**Comment by limod** [comment]
Thanks for the input @FlyingOnion! I overlooked this option in the code. This option affects all mounts, even non ETCD pods would put their data there then.
The only solution right now would be to mount a new disk directly under `/opt/rke/var/lib/etcd`
