### ISSUE TITLE
Deprecate Weave

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke#3338]
On August 10th 2023 it was agreed to deprecate Weave in rke 1.27 for different reasons:
1 - Weave has not released a new version since Jan 2021
2 - Weave is not supported in rke2/k3s, i.e. no migration path
3 - Apparently, no customer is really using weave CNI plugin

Chris Wayne and Will Godfrey agreed to this.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.8-head 01127d8
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
Rancher is properly warning user about weave plugin deprecation. I do not see a need for any other testing as of yet since only a deprecation warning has been issued and not yet fully removed.
![image](https://github.com/rancher/rke/assets/108360907/79ae0b7b-56db-46df-b955-d703dda08bdb)
