### ISSUE TITLE
Add kube-router CNI support

### ISSUE THREAD

**Issue by BloodyIron** [rancher/rke#3404]
Can we please have kube-router CNI support added already? I want to use kube-router as the CNI in Rancher without having to hack-job it.

**Comment by BloodyIron** [comment]
STILL INTERESTED PLEASE DONT REQUIRE I HAVE TO SPAM TO KEEP THIS OPEN!

**Comment by BloodyIron** [comment]
asdf

**Comment by aauren** [comment]
One of the kube-router maintainers here, let me know if there is something that you need from our side in order to help make this happen.

We do have the following issue open that we are actively working with another user of RKE2 to allow kube-router to more easily integrate with RKE2 like other network providers do by installing the plugins when they're missing: https://github.com/cloudnativelabs/kube-router/issues/1600

**Comment by BloodyIron** [comment]
It's more about the RKE devs "supporting" kube-router that I'm seeking here, so upstream Rancher can then do kube-router CNI stuff, without having to get greasy under the hood.

So not sure if you're directing that at me @aauren or the RKE devs, but that's where I'm coming from. :)

**Comment by aauren** [comment]
I've got ya. I was directing it at the RKE devs in case they needed the involvement from someone on the project.

**Comment by BloodyIron** [comment]
> I've got ya. I was directing it at the RKE devs in case they needed the involvement from someone on the project.

How generous of you! Yay! :D

**Comment by BloodyIron** [comment]
asdf

**Comment by aauren** [comment]
Not stale

**Comment by BloodyIron** [comment]
asdf

**Comment by MrBlaise** [comment]
Interested in this too

**Comment by chulucninh09** [comment]
Please keep this
