### ISSUE TITLE
Test if using cri-dockerd v0.3.5 removes the need for forked kubelet

### ISSUE THREAD

**Issue by superseb** [rancher/rke#3409]
As described in https://github.com/rancher/hyperkube#kubelet-binary-source-change, we are currently using a forked repository to generate the kubelet to solve this issue (https://github.com/rancher/rancher/issues/38816).

It was [filed upstream](https://github.com/Mirantis/cri-dockerd/issues/135) earlier, but it seems that in v0.3.5, a [PR was merged](https://github.com/Mirantis/cri-dockerd/pull/233) to solve this issue.

We should test if using upstream kubelet binary and cri-dockerd v0.3.5 solves the issue so we can remove the need for our fork.

**Comment by kinarashah** [comment]
Process wise, we would introduce a new k8s version in KDM (dev branch or forked, would need a new rke-tools branch if not using forked repo) that uses new cri-dockerd, and run the following tests: https://github.com/rancher/rancher/issues/38816#issuecomment-1444620534 
https://github.com/rancher/rancher/issues/38816#issuecomment-1446853343 

Note that the PR in cri-dockerd is new code change and doesn't fallback to the old behavior, so the performance won't be exactly identical but should be better than the original v1.24.10-rancher1-1 where the issue was first reported. We can compare metrics and then decide if we can rid of the forked kubelet or temporarily deliver both k8s versions (with and without forked kubelet) for users to test it out.

**Comment by kinarashah** [comment]
Commenting for bot

**Comment by justdan96** [comment]
Bump
