### ISSUE TITLE
No Peer Review on some commits?

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#468]
There are some commits being committed to master without going through peer review, this is a little bit concerning for folks who want to use RKE to stand up Kubernetes production environments. Shouldn't all commits, even from owners, go through a peer review process to ensure quality and stability of the commits before being merged to master?

**Comment by will-chan** [comment]
Hi @HighwayofLife, thanks for your interest in using RKE for your deployments and I definitely understand your concerns about the commits.  Although it may look like we don't do peer reviews at times, I can assure you we are definitely doing them.  It may come in the form of another engineer just doing your traditional "look-at-your-monitor-review" or the"LGTM" comments to them that happens in our own private slack.  It's not the ideal thing from letting you guys know what we are doing.  We are also actively testing them as well.

When we hit GA, it will become more formal.  Right now, we are in alpha stages and while we do believe it is of relatively good quality, I don't suggest you deploy this in your production environment quite just yet due to the fact we could make some significant changes possibly, between now and GA.  We are hoping to get a GA version of this end of April along with Rancher 2.0, if all things hold well.

**Comment by HighwayofLife** [comment]
Thanks for the explanation. We've been testing RKE since December and plan to deploy our production environment around the end of April as well.
