### ISSUE TITLE
Ability to use real hostname value for hostname from each host

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#63]
currently hostname_override defaults to address, and kube-api has option:

```"--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"```
which tell kube-api to skip hostname resolution for the nodes and use internal ip address and external if not found.

We should be able to fetch the hostname from the host, using a docker container with `--net=host`.

note: kubelet uses `/proc/sys/kernel/hostname` to get the hostname of the node.

**Comment by riaan53** [comment]
Hi @galal-hussein, do you still plan to add this feature or know of a workaround I can use for now? Thanks!

**Comment by PulseBright** [comment]
I was having issues with basically everything cluster-related throwing x509 errors because I used hostnames in my cluster.yml instead of IPs. I couldn't use `kubectl top` or `kubectl logs` (and some other commands I'm sure) because the certificates I had generated (using `rke certs generate-csr` and then 
 `rke up --custom-certs`) had no mention of IP addresses, only hostnames in the san's.

As a workaround, I've used this in my cluster.yml :
```
services:
  kube-api:
    [ ... ]
    extra_args:
      kubelet-preferred-address-types: "Hostname,InternalIP,ExternalIP"
```

Then I edited the deployment for metric-server to use `Hostname` instead of `InternalIP` first.
```
kubectl edit deployment metrics-server -n kube-system
```

For it to work, you need:
- Coredns is working and able to resolve hosts outside your cluster
- The cluster.yml uses the nodes' fqdn (`node1.domain.tld`, not just `node1`)
- The cluster's domain is different than your nodes' domain (for example, my nodes were in `domain.tld` and my cluster's domain is `cluster.domain.tld`)

**Also, since this includes editing the deployment by hand for metrics-server, it'll get undone by rke if you ever run the cluster setup again to update.**
