### ISSUE TITLE
Adding a sans to the config and running rke up does not update the certificates on the server

### ISSUE THREAD

**Issue by gucki** [rancher/rke#940]
**RKE version:**
v0.1.10

**Steps to Reproduce:**
Add a sans to the config. Run rke up. I'd expect the certificates on the server to be updated and reflect the added sans.

**Results:**
The certificates on the server are not updated. One has to delete them manually (kube-apiserver.pem) and then when running rke up, they are recreated with the new version.

**Comment by joshbenner** [comment]
See #450 and #865

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rke/issues/450. With cert rotation in place, you can update the sans and issue cert rotate command, and the certificates will be regenerated.

**Comment by lentzi90** [comment]
I'm not sure this should be closed. I did a cert rotation with `--rotate-ca` and a new "sans" entry in the config file but the new certificate does not include it. @alena1108

**Comment by lentzi90** [comment]
Ok, I figured it out. In order to add sans you have to first run `rke up` with the new entry in your rancher config. This adds it to the state stored in the `.rkestate` file. Once it is there you can do `rke cert rotate --rotate-ca` to get the new certificates.
Maybe this should be added to the documentation. Anyway, I how this helps anyone ending up here looking for answers.
