### ISSUE TITLE
rbd-nbd package missing in the kubelet image

### ISSUE THREAD

**Issue by gucki** [rancher/rke#944]
**RKE version:**
v0.1.10

The command/ package `rbd-nbd` is not installed in the kubelet image. So using `rbd-nbd` for ceph volumes is not possible. Would it be possible to have it added by default?

**Comment by superseb** [comment]
@gucki Can you confirm that this is only useful if rbd-nbd is v12+ (which is in backports repository) and not the default in Debian stretch which is v10? 

ref https://github.com/kubernetes/kubernetes/issues/73020

**Comment by gucki** [comment]
If you want to use rbd-nbd instead of krbd you need this package. So I think it'd be a good idea to always have it installed. Which version is hard to say, perhaps just the one of the distribution. If one needs a newer version he'll have to build his own image. That's what I'm doing for a couple of months now already.

**Comment by superseb** [comment]
The hyperkube image is built on Debian 9 (stretch), if we install the default packages, we end up with `10.2.11-2`, which is EOL since `2018-07-01` (https://github.com/ceph/ceph/blob/master/doc/releases/releases.yml#L83). If we would move to ceph's official repository, we can't install anything on stretch higher than luminous (v12) because the packages are not built for stretch, see http://lists.ceph.com/pipermail/ceph-users-ceph.com/2018-June/027097.html. Luminous has a target date for EOL of `2019-06-01`. (https://github.com/ceph/ceph/blob/master/doc/releases/releases.yml#L70)

There is an unofficial mirror hosted at `croit.io`, but if people want to support this for their workloads, I would suggest to incorporate that in their own custom images. Even when using it, you can still use any of the active ceph releases, which is then up to the person who wants to use it.

Even for Debian 10 (buster), distribution packages gives you `12.2.11` and there are also no official ceph packages made for buster. I think without an official solution, we shouldn't do anything non-official like adding custom repositories (croit) or install other distro packages (bionic) and let people decide for themselves what they agree on using.
